learning_log/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
    path('users/', include('users.urls')),
]

learning_logs/urls.py
# Define padrões de URL para learning_logs

from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'learning_logs'
urlpatterns = [
    # Página inicial
    path('', views.index, name='index'),

    path('comunidade', views.comunidade, name='comunidade'),

    # mostra todos os assuntos
    path('topics/', views.topics, name='topics'),

    # Página de detalhes para um único assunto
    path('topics/<int:topic_id>', views.topic, name='topic'),

    # Página para adicionar um novo assunto
    path('new_topic', views.new_topic, name='new_topic'),

    # Página para adicionar uma nova entrada
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),

    # página para editar uma entrada
    path('edit_entry/<int:entry_id>', views.edit_entry, name='edit_entry'),

    # página, para somente ver as entradas de cada tópico
    path('resgistros_topico/<int:topic_id>', views.registros_topico, name='registro_topico'),

]

users/urls.py
""" Define URL patters for users """

from django.urls import path, include

from users import views

app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('sair_login/', views.sair_lgin, name='sair_login'),
    path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    """Um assunto sobre o qual o usuário está aprendendo
    """
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Devolve uma representação em string do modelo.
        """
        return self.text


class Entry(models.Model):
    """Algo específico sobre um assunto
    """
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """
        Devolve a representação de uma string modelo.
        """

        if len(self.text) < 45:
            return self.text
        else:
            return self.text[:50] + '...'

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from learning_logs.models import Topic, Entry
from django.contrib.auth.decorators import login_required
from .forms import TopicForm, EntryForm
from django.http import Http404


def check_topic_owner(topic, request):
    if topic.owner != request.user:
        raise Http404


def index(request):

    """  A página inicial de Learning log, sem usuário estar logado"""

    return render(request, 'learning_logs/index.html')


@login_required
def comunidade(request):
    topics = Topic.objects.order_by('date_added')  # somente para fazer funcionar até sexta

    context = {'topics': topics}
    return render(request, 'learning_logs/comunidade.html', context)


@login_required
def topics(request):
    """ Mostra todos os assuntos """
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, topic_id):
    """ Mostra um único assunto e todas as suas entradas. """
    topic = get_object_or_404(Topic, id=topic_id)

    check_topic_owner(topic, request) # confere se o usário da requisição é o dono do tópico

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
    """ Adiciona um novo tópico."""
    if request.method != 'POST':
        # nenhum dado submetido, cria um formulário em branco
        form = TopicForm()
    else:
        # dados de um POST submetido, procesa os dados
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()

            return redirect('learning_logs:topics')

    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """ Acrescenta uma nova entrada para um assunto em particular. """
    topic = Topic.objects.get(id=topic_id)

    check_topic_owner(topic, request)

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)
    # Display a blank or invalid form.
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """ Edita uma entrada existente """
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    check_topic_owner(topic, request)

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)


@login_required
def registros_topico(request, topic_id):

    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/registros_topicos.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout, login
from django.contrib.auth.forms import UserCreationForm


def sair_lgin(request):
    logout(request)
    return render(request, 'users/sair_login.html')


def register(request):
    """ Register new user. """
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('learning_logs:index')

    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
        shrink-to-fit=no">
    <title>Learning Log</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

        <a class="navbar-brand" href="{% url 'learning_logs:index'%}">
            Learning Log</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'learning_logs:comunidade'%}">Comunidade</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'learning_logs:topics'%}">Meus tópicos</a>
                </li>

            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text">Olá, {{ user.username }}.</span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:sair_login' %}">Log out</a>
                        </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
        </div>
        <div>
        {% block content %}{% endblock content %}
    </div>

</body>

</html>

learning_logs/templates/learning_logs/comunidade.html
{% extends 'learning_logs/base.html' %}
{% block page_header %}
    <div class="jumbotron">
        <h1 class="display-4">Postagens da comunidade.</h1>

    <p class="lead">Nesta página se encontra todos os tópicos de toda a comunidade dos usuários</p>

    </div>
{% endblock page_header %}
{% block content %}
    <ul>
        {% for topic in topics %}
            <li>
                <p></p>
                <a  href="{% url 'learning_logs:registro_topico' topic.id %}">{{ topic }}
                    <br>Adicionado em: {{ topic.date_added }}

                </a>
            </li>
        {% empty %}
            <li>Não há tópicos ainda.</li>
        {% endfor %}
    </ul>

{% endblock content %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}

{% block content %}
    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a> </p>

    <p>Edit entry:</p>

    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">save changes</button>
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}
{% block page_header %}
    <div class="jumbotron">
        <h1 class="display-3">Track your learning</h1>

    <p class="lead">Make your own Learning Log, and keep a list of the
            topics you're learning about. Whenever you learn something new
            about a topic, make an entry summarizing what you've learned.</p>

    {% if user.is_authenticated %}
    {% else %}
        <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">
            Register &raquo;
        </a>
    {% endif %}
    </div>
{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}

{% block content %}
    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

    <p>Add a new entry:</p>
    <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">add entry</button>
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}
    <p>Add a new topic:</p>

    <form action="{% url 'learning_logs:new_topic' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">add topic</button>
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/registros_topicos.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
    <h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}

    <ul>
        {% for entry in entries %}
            <div class="card mb-3">
                <h4 class="card-header">
                    {{ entry.date_added | date:'M d, Y H:i' }}

                </h4>
                <div class="card-body">
                    {{ entry.text | linebreaks }}
                </div>
            </div>
        {% empty %}
            <p>Não há entradas ainda</p>
        {% endfor %}
    </ul>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
    <h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}

    <p>Tópico: {{ topic }}</p>

    <p>Entries:</p>
    <p>
        <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
    </p>
    <ul>
        {% for entry in entries %}
            <div class="card mb-3">
                <h4 class="card-header">
                    {{ entry.date_added | date:'M d, Y H:i' }}
                    <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">
                        Editar entrada</a></small>
                </h4>
                <div class="card-body">
                    {{ entry.text | linebreaks }}
                </div>
            </div>
        {% empty %}
            <p>Não há entradas ainda</p>
        {% endfor %}
    </ul>

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
    <h1>Meus topicos</h1>
{% endblock page_header %}


{% block content %}

    <ul>
        {% for topic in topics %}
            <li><h3>
                <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
                <br>
            </h3></li>
        {% empty %}
            <li><h3>Não há tópicos ainda.</h3></li>
        {% endfor %}
    </ul>

    <h3><br><a href="{% url 'learning_logs:new_topic' %}">Add a new topic:</a></h3>

{% endblock content %}

users/templates/users/sair_login.html
{% extends 'learning_logs/base.html' %}

{% block content %}
    <p>You have been logged out. Thank you for visiting!</p>
{% endblock content %}